version: '3.9'

services:
  shopping-platform-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/shopping-platform
      - MONGODB_INIT=true
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    extends:
      file: ./docker-compose/common.yml
      service: mongodb
    ports:
      - 27017:27017