spring:
  data:
    mongodb:
      uri: 'mongodb://root:password@localhost:27017/shopping-platform?authSource=admin&readPreference=primary&ssl=false&directConnection=true'
  docker:
    compose:
      file: './docker-compose/docker-compose-local.yml'