server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: local
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method